Ans 1)

In [1]:
# Yes, there is a difference in the data types of the variables list_ and array_list.

# The variable list_ is a regular Python list, and its elements are strings.

# The variable array_list is a NumPy array, and since the elements in the original list were strings, the elements in the NumPy array will also be strings.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Ans 2)

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)
print("Data type of each element in list_:")
for element in list_:
    print(type(element))
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Ans 3)

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

# Printing the data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Printing the data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Ans 4)

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# (i) Finding the shape of num_array
shape = num_array.shape

# (ii) Finding the size of num_array
size = num_array.size
print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


Ans 5)

In [5]:
import numpy as np
zero_matrix = np.zeros((3, 3), dtype=int)
print(zero_matrix)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


Ans 6)

In [6]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
